# Book settings
title: System & AI 2022
author: Eyal Soreq
logo: images/figures_LOGO.png
execute:
  execute_notebooks: force
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: false
  use_issues_button: true
  use_edit_page_button: false
  navbar_number_sections : false
  baseurl : "https://esoreq.github.io/SystemAI2022/"  # The base URL where your book will be hosted. 
  comments:
    hypothesis: false
    utterances: false
    repo: false
    dokieli: false
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

repository: 
  url          : https://esoreq.github.io/SystemAI2022/
  path_to_book : ""
  branch       : master

sphinx:
  config:
    html_show_copyright: true
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_heading_anchors : 5
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - tasklist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - substitution

launch_buttons:
  notebook_interface        : ""  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)