name: dcarte_tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - alabaster
  - jupyter-book
  - matplotlib
  - numpy
  - pandas
  - myst-parser

  - sphinx==4.4.0
  - sphinx-book-theme==0.1.10
  - sphinx-comments==0.0.3
  - sphinx-copybutton==0.5.0
  - sphinx-external-toc==0.2.3
  - sphinx-jupyterbook-latex==0.4.6
  - sphinx-multitoc-numbering==0.1.3
  - sphinx-panels==0.6.0
  - sphinx-thebe==0.1.1
  - sphinx-togglebutton==0.2.3
  - sphinxcontrib-applehelp==1.0.2
  - sphinxcontrib-bibtex==2.4.1
  - sphinxcontrib-devhelp==1.0.2
  - sphinxcontrib-htmlhelp==2.0.0
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-qthelp==1.0.3
  - sphinxcontrib-serializinghtml==1.1.5
  - pip:
    - linkify
    - linkify-it-py